# Don't insert a blank line between shell prompts
add_newline = false
format = """
[â”Œ](bold #C74DED) [ó°„› ](bold #C74DED) '$directory' de $hostname ($all)\
[â””>](bold #C74DED) $character
"""
[character] 
success_symbol = "[ï”ï„…](bold purple)"
error_symbol = "[ï”ï„…](red)"

# '$directory' de $hostname per $username
[username]
format = "[$user](bold dimmed blue) "
show_always = false # don't show it 
disabled = false

[hostname]
#format = 'de [$hostname](bold dimmed blue)'
format = '[$hostname](bold purple)'
ssh_only = false
disabled = false

[directory]
read_only = " ï ½"
format = '[$path](bold cyan)'
truncation_length = 4
truncation_symbol = "../"
truncate_to_repo = false # truncates directory to root folder if in github repo
# style = "bold italic blue"


[cmd_duration]
min_time = 30 # in milis
show_milliseconds = false
disabled = false


# Edited Nerd font preset
[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[git_branch]
symbol = "ï˜ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "î¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "
